### ISSUE TITLE
Signup goes to login

### ISSUE THREAD

**Issue by iangcarroll** [ColemanGariety/OpenHacker#2]
Can't signup if you have to login...

**Comment by cp** [comment]
@snapapps Thanks Ian. Put this together in an hour or so, so there are going to be bugs. It's a work in progress.

**Comment by iangcarroll** [comment]
I'll submit some pull requests tommorow. :)

On Sunday, February 24, 2013, Colby Aley wrote:

> @snapapps https://github.com/snapapps Thanks Ian. Put this together in
> an hour or so, so there are going to be bugs. It's a work in progress.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ColbyAley/The-Challenge/issues/2#issuecomment-14024940.

## 

Ian Carroll
Snap Studio Design

**Comment by cp** [comment]
@snapapps Ok, cool.

**Comment by iangcarroll** [comment]
Gah, I'll work on it tomorrow.
