### ISSUE TITLE
WebKit flickering on the repo checker animations

### ISSUE THREAD

**Issue by ColemanGariety** [ColemanGariety/OpenHacker#28]
Happens on non-retina displays.

**Comment by cp** [comment]
I cant replicate this in Chrome on my MBA.

**Comment by ColemanGariety** [comment]
Safari?

~ Jackson Gariety

Code is poetry.
http://jacksongariety.com/
@JacksonGariety

**Comment by cp** [comment]
Can't replicate on Safari either.

**Comment by ColemanGariety** [comment]
Retina probs i guess.

~ Jackson Gariety

Code is poetry.
http://jacksongariety.com/
@JacksonGariety

**Comment by ColemanGariety** [comment]
Fixed by adding z-index: 1; to header .inner and -webkit-transform: translateZ(0); to the header and footer. Worst webkit bug I've ever seen though. Confirmed only present on Safari 6.0.x and Intel HD Graphics 4000 (not just rMBP).

**Comment by cp** [comment]
Weird. I have that same GFX card, and tested in on Safari (latest version).

**Comment by ColemanGariety** [comment]
What version do you have?

**Comment by ColemanGariety** [comment]
Also are you watching the header element? That's what flickers.

**Comment by cp** [comment]
Nevermind, I could replicate it.

**Comment by ColemanGariety** [comment]
Fuck, my fixes causes even worse issue on the voting page. FUCK WEBKIT.

**Comment by cp** [comment]
Opera ftw, amirite?

**Comment by ColemanGariety** [comment]
Even worse. That'll have bugs too and it'll make it even more confusing. But yeah in general blink is more stable.

**Comment by cp** [comment]
I love how I totally edited my comment.

**Comment by ColemanGariety** [comment]
wtf, you dick. Now I sound like a retard who thinks Opera runs on blink.

**Comment by ColemanGariety** [comment]
Odd. If the header inner's max-width is greater than 2000px the stuttering is present. If it's exactly 2000px or anything less, it doesn't appear. FUCK WEBKIT

**Comment by cp** [comment]
You can edit your comment too. I also love how Github comments update in real time.

**Comment by ColemanGariety** [comment]
New development... all of these bug ONLY APPEAR if your browser windows is > 2000px wide. WHAT THE FUCK WEBKIT!?

**Comment by ColemanGariety** [comment]
Well I've spent almost 2 hours on this. Fuck.

The best I've managed to do is get it to flash only once on page load of the /submit page in Safari 6.0.x. It bothers me, but oh well.

**Comment by ColemanGariety** [comment]
The answer: WebKit has a maximum texture rendering size of 2000px. So if your browser is great than 2000px, it has to generate two textures. But there's a bug in Safari where it tries to draw the rendering element after completion of rendering a texture, but it doesn't account for when more than one texture has to render, so it tries to display the openGL element before its texture is ready and you get this "flashing".

The answer is to wait for Safari to be updated with this fix. For the moment it caches the textures with JavaScript so it only has to flash once when the first check mark comes up.

If we had position: absolute; on the header this wouldn't happen since it wouldn't have to render the header in 3D.

Do we move to an absolute header that stays at the top of the page to solve a bug seen by .01% of the population (Safari 6, screen wider than 2000px)? Or do we settle for the flash?
