### ISSUE TITLE
What is variables.yml?

### ISSUE THREAD

**Issue by jasnow** [ColemanGariety/OpenHacker#73]
What is variables.yml file? 

Can you please add something about it to the README file.

"rake db:setup" wants it.

Thanks.

**Comment by ColemanGariety** [comment]
To get OH up and running on your machine. You'll need to add a `variables.yml` file to the `config` folder which contains three constants:

GITHUB_KEY:
GITHUB_SECRET:
GOSQUARED_ACCT:

**Comment by ColemanGariety** [comment]
Closed with commit 00f94ae0a9

**Comment by jasnow** [comment]
Is this where I find out more about how to set the GOSQUARED_ACCT variable?  https://www.gosquared.com

**Comment by ColemanGariety** [comment]
Yeah, it's for tracking info. But If I were you I'd just look for where the GOSQUARED_ACCT variable is used and just wrap it in an if statement so that it doesn't run if there's no ACCT code present.
